/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : bigint,
  'status' : string,
  'serviceName' : string,
  'clientName' : string,
  'owner' : Principal,
  'date' : string,
  'createdAt' : bigint,
  'time' : string,
  'serviceId' : bigint,
}
export interface Service {
  'id' : bigint,
  'priceAmount' : bigint,
  'name' : string,
  'description' : string,
  'durationMinutes' : bigint,
  'category' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelAppointment' : ActorMethod<
    [bigint],
    { 'ok' : Appointment } |
      { 'err' : string }
  >,
  'checkSlotAvailable' : ActorMethod<[string, string], boolean>,
  'createAppointment' : ActorMethod<
    [bigint, string, string, string, string],
    { 'ok' : Appointment } |
      { 'err' : string }
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyAppointments' : ActorMethod<[], Array<Appointment>>,
  'getService' : ActorMethod<[bigint], [] | [Service]>,
  'getServices' : ActorMethod<[], Array<Service>>,
  'getServicesByCategory' : ActorMethod<[string], Array<Service>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];
