/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'serviceName' : IDL.Text,
  'clientName' : IDL.Text,
  'owner' : IDL.Principal,
  'date' : IDL.Text,
  'createdAt' : IDL.Int,
  'time' : IDL.Text,
  'serviceId' : IDL.Nat,
});
export const Service = IDL.Record({
  'id' : IDL.Nat,
  'priceAmount' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'durationMinutes' : IDL.Nat,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelAppointment' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : Appointment, 'err' : IDL.Text })],
      [],
    ),
  'checkSlotAvailable' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], ['query']),
  'createAppointment' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Appointment, 'err' : IDL.Text })],
      [],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
  'getService' : IDL.Func([IDL.Nat], [IDL.Opt(Service)], ['query']),
  'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
  'getServicesByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Service)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'serviceName' : IDL.Text,
    'clientName' : IDL.Text,
    'owner' : IDL.Principal,
    'date' : IDL.Text,
    'createdAt' : IDL.Int,
    'time' : IDL.Text,
    'serviceId' : IDL.Nat,
  });
  const Service = IDL.Record({
    'id' : IDL.Nat,
    'priceAmount' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'durationMinutes' : IDL.Nat,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelAppointment' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : Appointment, 'err' : IDL.Text })],
        [],
      ),
    'checkSlotAvailable' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'createAppointment' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Appointment, 'err' : IDL.Text })],
        [],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyAppointments' : IDL.Func([], [IDL.Vec(Appointment)], ['query']),
    'getService' : IDL.Func([IDL.Nat], [IDL.Opt(Service)], ['query']),
    'getServices' : IDL.Func([], [IDL.Vec(Service)], ['query']),
    'getServicesByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Service)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };
